<link rel="stylesheet" href="user/css/bootstrap.min.css">
<link rel="stylesheet" href="user/css/owl.carousel.min.css">
<link rel="stylesheet" href="user/css/ticker-style.css">
<link rel="stylesheet" href="user/css/flaticon.css">
<link rel="stylesheet" href="user/css/slicknav.css">
<link rel="stylesheet" href="user/css/animate.min.css">
<link rel="stylesheet" href="user/css/magnific-popup.css">
<link rel="stylesheet" href="user/css/fontawesome-all.min.css">
<link rel="stylesheet" href="user/css/themify-icons.css">
<link rel="stylesheet" href="user/css/slick.css">
<link rel="stylesheet" href="user/css/nice-select.css">
<link rel="stylesheet" href="user/css/style.css">
