<link rel="stylesheet" href="{{ asset('/public/user/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('/public/user/css/owl.carousel.min.css') }}">
<link rel="stylesheet" href="{{ asset('/public/user/css/ticker-style.css') }}">
<link rel="stylesheet" href="{{ asset('/public/user/css/flaticon.css') }}">
<link rel="stylesheet" href="{{ asset('/public/user/css/slicknav.css') }}">
<link rel="stylesheet" href="{{ asset('/public/user/css/animate.min.css') }}">
<link rel="stylesheet" href="{{ asset('/public/user/css/magnific-popup.css') }}">
<link rel="stylesheet" href="{{ asset('/public/user/css/fontawesome-all.min.css') }}">
<link rel="stylesheet" href="{{ asset('/public/user/css/themify-icons.css') }}">
<link rel="stylesheet" href="{{ asset('/public/user/css/slick.css') }}">
<link rel="stylesheet" href="{{ asset('/public/user/css/nice-select.css') }}">
<link rel="stylesheet" href="{{ asset('/public/user/css/style.css') }}">
